name: Bug Report
description: Report any problems or bugs to contribute to the project's improvement
labels: ["bug"]

body:
  - type: checkboxes
    attributes:
      label: Have you checked? *
      description: Please check if this bug is already reported in open or closed issues.
      options:
        - label: I have searched for similar bugs in existing issues.
          required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: What is the problem or unexpected behavior?
      placeholder: e.g., The release files are missing, or the rename script crashes on certain files.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug? Please be specific.
      placeholder: e.g., Run the script on files named like this, or try to download the latest release.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: What should happen?
      description: Describe the expected behavior or outcome.
      placeholder: e.g., The script should rename all files correctly, or the release should include all files.
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional information (optional)
      description: Screenshots, error messages, logs, or anything else that might help.
      placeholder: e.g., Terminal output, error traceback, or screenshots.
    validations:
      required: false
