name: Add a Wallpaper to the Collection
description: Share a cool wallpaper and help grow the collection!
labels: ["wallpaper", "feature-request"]

body:
  - type: checkboxes
    attributes:
      label: Before You Submit *
      description: Please check all the boxes to make sure your wallpaper follows the rules.
      options:
        - label: The wallpaper is at least 1920x1080 in size.
          required: true
        - label: The image is clear and not blurry or pixelated.
          required: true
        - label: The file is a .jpg, .jpeg, .png, or .gif.
          required: true

  - type: textarea
    id: wallpaper_uploads
    attributes:
      label: Upload your wallpaper(s) here and mention their categories above each image
      description: |
        Drag and drop your wallpaper files below, then **type the category folder name above each image.**
        For example:

        ```
        Sci-fi
        [upload your Sci-fi wallpaper here]

        Nature
        [upload your Nature wallpaper here]
        ```

        Make sure your images upload correctly and display properly before submitting.
    validations:
      required: true


  - type: textarea
    id: extra_info
    attributes:
      label: Anything else to add?
      description: Add any extra info, credits, or notes here (if needed).
    validations:
      required: false

